improve code

diff --git a/Runfile.template b/Runfile.template
--- a/Runfile.template
+++ b/Runfile.template
@@ -294,14 +294,34 @@ __fn_list_check_loop() {
 	local path_for=""
 	local path_now=""
 	local path_pre=""
+	__path_auto_format(){
+		path_now=$( pwd )
+		if [[ "${path_pre}" != "${path_now}" ]]; then
+			path_pre="${path_now}"
+			#
+			path_for="$( echo "${path_now}" | sed -e s@$HOME@'~'@g )"
+			path_for="${GREEN}$( basename ${path_for} ) "
+		fi
+	}
 	#
 	local git_info_start=$(_fn_git_info_start)
 	local git_info_end=$(_fn_git_info_end)
 	local sign=$( if [[ "$USER" != "root" ]]; then echo "${BLUE}\$ "; else echo "${RED}\# "; fi )
 	
-	local arrow="${GREEN}➜ [r] "
-	
-	
+	local arrow_red="${RED}➜ [r] "
+	local arrow_green="${GREEN}➜ [r] "
+	local arrow=${arrow_green}
+	__arrow_auto_set() {
+		exitcode=$?
+		# echo "__arrow_auto_set -> exitcode: $exitcode"
+		if [[ $exitcode -gt 0 ]]; then 
+			arrow=${arrow_red}
+			# echo "arrow to red"
+		else 
+			arrow=${arrow_green}
+			# echo "arrow to green"
+		fi
+	}
 	
 	while true ; do
 
@@ -310,13 +330,15 @@ __fn_list_check_loop() {
 			#echo "Runfile was changed"
 			_fn_reload
 		fi
-		path_now=$( pwd )
-		if [[ "${path_pre}" != "${path_now}" ]]; then
-			path_pre="${path_now}"
-			#
-			path_for="$( echo "${path_now}" | sed -e s@$HOME@'~'@g )"
-			path_for="$( basename ${path_for} ) "
-		fi
+
+		__path_auto_format
+		# path_now=$( pwd )
+		# if [[ "${path_pre}" != "${path_now}" ]]; then
+		# 	path_pre="${path_now}"
+		# 	#
+		# 	path_for="$( echo "${path_now}" | sed -e s@$HOME@'~'@g )"
+		# 	path_for="${GREEN}$( basename ${path_for} ) "
+		# fi
 		
 		# -e for tab completion on dir or file name
 		read -e -p "${arrow}${path_for}${git_info_start}$( _fn_git_info_mid )${git_info_end}$(_fn_git_status)${sign}${COLOR_RESET}" cmd args
@@ -346,7 +368,11 @@ __fn_list_check_loop() {
 					time eval alias_${cmd} "${args}"
 				else
 					echo "command \"${cmd}\" couln't be found!"
+					# set $? - return code without exit shell
+					# actually it run in subshell and exit subshell
+					( exit 1 ) 
 				fi
+				__arrow_auto_set
 		esac
 	done
 }
diff --git a/test/Runfile b/test/Runfile
--- a/test/Runfile
+++ b/test/Runfile
@@ -10,7 +10,44 @@ abc2() {
 	echo "abc2 task"
 }
 
+exitcode() {
+	echo "this task will failed"
+	( exit 33 ) # return exit code without close shell - actualy exit sub shell
+}
 
+# test variable scope
+# -> varialbe x can be change inside tt function and sub function
+# but outside is not change, it like inside function it create another 
+# variable x after the line: x="first"
+x="out"
+tt() {
+	echo -e "[tt] init: x=$x"
+	x="first"
+	echo -e "[tt] changed: x=$x"
+	tt1() {
+		echo -e "\t[tt1] x=$x"
+		x="second"
+		echo -e "\t[tt1] =$x"
+	}
+	tt1
+	echo -e "[tt]=$x => changed inside: $( [[ "$x" == "out" ]] && echo "no" || echo "yes" )"
+}
+tt_check() {
+	echo -e "changed outside? $( [[ "$x" != "out" ]] && echo "no" || echo "yes" )"
+}
+
+tt2() {
+	echo -e "[tt2] init: x=$x"
+	local x="first"
+	echo -e "[tt2] changed: x=$x"
+	tt22() {
+		echo -e "\t[tt22] x=$x"
+		x="second"
+		echo -e "\t[tt22] =$x"
+	}
+	tt22
+	echo -e "[tt2]=$x => changed: $( [[ "$x" == "out" ]] && echo "no" || echo "yes" )"
+}
 
 
 ##endregion USER =================================================
