change from exit to return to the caller if callback function return value > 0

diff --git a/plugins/utils_1 b/plugins/utils_1
--- a/plugins/utils_1
+++ b/plugins/utils_1
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # rf_dir_recurse loop & print a folder recusively,
-# and will exit when return value != 0
+# and will return to caller when return value != 0
 rf_dir_recurse() {
 	local dir=${1:-"."}
 	local fnFileCallback=${2:-}
@@ -12,7 +12,7 @@ rf_dir_recurse() {
 				# call the callback function and pass current directory path to it
 				fnDirCallback ${f}
 				if [[ $? != 0 ]]; then
-					exit $?
+					return $?
 				fi
 			fi
 			rf_dir_recurse "${f}"
@@ -21,7 +21,7 @@ rf_dir_recurse() {
 				# call the callback function and pass current directory path to it
 				fnFileCallback ${f}
 				if [[ $? != 0 ]]; then
-					exit $?
+					return $?
 				fi
 			fi
         fi
